### PR TITLE
Egoscale update [wip]

### PR DESCRIPTION
**Pull request by greut**
internal review, do not merge.

The big change is this...

```diff
-defaultImage             = "Linux Ubuntu 16.04 TLS 64-bit"
+defaultImage             = "Linux Ubuntu 16.04 LTS 64-bit"
```

Then the security group created is also different.

screenshot from 2018-01-29 09-15-50

The previous one had 3376 which is the original Docker Swarm.

### CODE REVIEW

**Comment by marcaurele** [comment]
Why removing the swarm port?

**Comment by greut** [comment]
@marcaurele 3376 is the old swarm port: https://docs.docker.com/swarm/plan-for-production/#security

**Comment by greut** [comment]
> - TCP port 2377 for cluster management communications
> - TCP and UDP port 7946 for communication among nodes
> - UDP port 4789 for overlay network traffic
>
> https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts

**Comment by greut** [comment]
I've added the 7946 in TCP mode.

**Comment by marcaurele** [comment]
> - Inbound 2375/tcp. This allows Docker Engine CLI commands direct to the Engine daemon.
> - Inbound 3375/tcp. This allows Engine CLI commands to the swarm manager.

**Comment by marcaurele** [comment]
> If your swarm cluster is configured for TLS, replace 2375 with 2376, and 3375 with 3376

**Comment by greut** [comment]
@marcaurele I've put back 3376 and 3377, thanks for the review!

**Pull request closed without merging**
